project:
  type: website
  output-dir: docs

website:
  title: "jake1705"
  navbar:
    left:
      - href: Research Design.qmd
        text: Home

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



